name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.15.4'
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: starter-kit-ts-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          starter-kit-ts-${{ hashFiles('**/package-lock.json') }}
          starter-kit-ts-
    - run: ./bin/check-node.sh
    - run: npm ci
      env:
        CYPRESS_INSTALL_BINARY: 0
    - run: npm run lint
    - run: npm run test
    - uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: false
        tags: textbook/starter-kit-ts
  e2e:
    runs-on: ubuntu-18.04
    needs: build
    strategy:
      matrix:
        node: [ '10', '12', '14' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: starter-kit-ts-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          starter-kit-ts-${{ hashFiles('**/package-lock.json') }}
          starter-kit-ts-
    - run: npm ci
    - run: npm run e2e
    - run: npm run e2e:dev
  deploy:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    needs: e2e
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.15.4'
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: starter-kit-ts-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          starter-kit-ts-${{ hashFiles('**/package-lock.json') }}
          starter-kit-ts-
    - run: npm ci
      env:
        CYPRESS_INSTALL_BINARY: 0
    - run: npm run build
    - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: starter-kit-ts
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
    - uses: d3sandoval/cloud-foundry-action@1.1.1
      with:
        args: push
      env:
        CF_API: https://api.run.pcfone.io
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        CF_TARGET_ORG: pivot-jsharpe
        CF_TARGET_SPACE: development
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
